name: CI - Testes

on:
  pull_request:
    branches:
      - release

  push:
    branches:
      - release
      
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 24]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm test

      - name: Criar arquivo .env
        run: echo "EXPO_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env

      - name: Build do projeto
        run: npx expo export --platform web

      - name: Desabilitar Jekyll
        run: touch dist/.nojekyll

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4

  
  # Build do APK
  android-build:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Criar arquivo .env
        run: echo "EXPO_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Gerar projeto nativo Android
        run: npx expo prebuild --platform android --clean

      - name: Dar permissão de execução ao gradlew
        run: chmod +x android/gradlew

      - name: Build do APK Release
        run: cd android && ./gradlew assembleRelease

      - name: Upload do APK como artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 30

  # Release do APK
  create-release:
    if: github.event_name == 'push'
    needs: [test,android-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Baixar artefato do APK
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk
          path: ./

      - name: Criar GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Release automática #${{ github.run_number }}

            ### Arquivos incluídos:
            - app-release.apk
          files: |
            app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  # Docker
  docker-build:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Criar .env
        run: echo "EXPO_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env

      - name: Gerar build web
        run: npx expo export --platform web

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tmdb-app:latest
